<template>
  <main class="py-8">
    <div class="container m-auto px-4 grid gap-y-8">
      <section>
        <h1 class="text-4xl font-medium mb-4">
          Summary of {{ lattice.title }}
        </h1>
        <h3>
          Data is generated by
          <a
            href="https://www.aps.anl.gov/Accelerator-Operations-Physics/Software"
            >elegant</a
          >
        </h3>
      </section>

      <section>
        <h2 class="text-2xl font-medium mb-4">Info</h2>
        <Table :data="metaData" />
      </section>

      <section>
        <h2 class="text-2xl font-medium mb-4">Optical Functions Plot</h2>
        <img :src="`/${$baseURL}/summary/${name}/elegant/twiss.svg`" />
      </section>

      <section>
        <h2 class="text-2xl font-medium mb-4">
          Global Machine & Lattice Parameter
        </h2>
        <div class="grid gap-4 lg:grid-cols-2">
          <Table :data="twiss_tables.machine_parameter" />
          <Table :data="twiss_tables.global_parameter" />
        </div>
      </section>

      <section>
        <h2 class="text-2xl font-medium mb-4">Detailed Lattice Parameter</h2>
        <div class="grid gap-4 lg:grid-cols-2">
          <Table :data="twiss_tables.twiss_x" />
          <Table :data="twiss_tables.twiss_y" />
        </div>
      </section>

      <section>
        <h2 class="text-2xl font-medium mb-4">Chromaticity</h2>
        <figure>
          <img :src="`/${$baseURL}/summary/${name}/elegant/chroma.svg`" />
          <figcaption>
            Chromaticity from the ”twiss output” command (3rd order
            calculation).
          </figcaption>
        </figure>
      </section>
    </div>
  </main>
</template>

<script>
import Table from "../components/Table.vue";

export default {
  name: "SummaryElegant",
  components: { Table },
  data() {
    return {
      name: "",
      lattice: {
        name: "abc",
        author: "abc",
        title: "abc",
        description: "abc",
      },
      twiss_tables: {},
    };
  },
  computed: {
    metaData() {
      return [
        ["Title", this.lattice.title],
        ["Author", this.lattice.author],
        ["Name", this.lattice.name],
        ["Description", this.lattice.description],
      ];
    },
  },
  // tODO: make sure this updates if url changes
  async created() {
    console.log("start change");
    this.name = this.$route.params.name;
    const response = await fetch(
      `/${this.$baseURL}/summary/${this.name}/elegant/twiss_tables.json`
    );
    this.twiss_tables = await response.json();
    console.log("end change");
  },
};
</script>