<template>
  <main class="py-8" v-if="this.lattice !== null">
    <div class="container m-auto px-4">
      <section class="mb-8">
        <h1 class="text-2xl font-medium mb-4">
          Summary of {{ lattice.title }}
        </h1>
        <h3>
          Data is generated by
          <a
            class="font-semibold text-primary-500"
            :href="nameMap[this.simulation]"
            target="_blank"
          >
            {{ simulation }}
          </a>
        </h3>
      </section>
      <div class="grid gap-8 xl:grid-cols-2">
        <Card>
          <LatticeInfo :lattice="lattice" />
        </Card>
        <Card v-if="latticeInfo !== null">
          <h2 class="text-xl font-medium mb-4">{{ latticeInfo[0] }}</h2>
          <Table :data="latticeInfo[1]" />
        </Card>

        <Card
          class="flex flex-col"
          v-for="(table, index) in twiss_tables"
          :key="index"
        >
          <h2 class="text-xl font-medium mb-4">{{ table[0] }}</h2>
          <div
            class="flex-grow grid gap-4"
            :class="{ 'lg:grid-cols-2': table[1].length > 1 }"
          >
            <div v-for="(sub, index) in table[1]" :key="index">
              <img
                class="w-full"
                v-if="typeof sub === 'string'"
                :src="this.content_path + sub"
                data-zoomable="true"
              />
              <Table v-else class="w-full" :data="sub" />
            </div>
          </div>
        </Card>
      </div>
    </div>
  </main>
</template>

<script>
import Card from "../components/Card.vue";
import Table from "../components/Table.vue";
import LatticeInfo from "../components/LatticeInfo.vue";

export default {
  name: "Summary",
  components: { Card, Table, LatticeInfo },
  data() {
    return {
      name: "",
      lattice: null,
      latticeInfo: null,
      simulation: "",
      twiss_tables: {},
      content_path: "",
      nameMap: {
        elegant:
          "https://www.aps.anl.gov/Accelerator-Operations-Physics/Software",
        madx: "http://madx.web.cern.ch/madx/",
        apace: "https://github.com/andreasfelix/apace",
      },
    };
  },
  async created() {
    await this.fetchData();
  },
  watch: {
    $route: "fetchData",
  },
  methods: {
    async fetchData() {
      this.name = this.$route.params.name;
      this.namespace = this.$route.params.namespace;
      this.simulation = this.$route.params.simulation;
      const base_path = `${this.$dataURL}/${this.namespace}/${this.name}/`;
      const content_path = base_path + `${this.simulation}/`;
      let response = await fetch(content_path + "twiss_tables.json");
      this.twiss_tables = await response.json();
      response = await fetch(base_path + "index.json");
      this.lattice = await response.json();
      response = await fetch(base_path + "lattice_info.json");
      this.latticeInfo = await response.json();
      // defer to make sure twiss_tables is loaded before imgs are updated
      this.content_path = content_path;
    },
  },
};
</script>
